### ISSUE TITLE
Proposed sources

### ISSUE THREAD

**Issue by smad2005** [i2um1/NyaaViewer#1]
# English
- MangaReader
- MangaFox
- MangaEden (EN)
- MangaHere
- Batoto (EN)
# Italian
- MangaEden (IT)
- Itascan
- Batoto (IT)
# Vietnamese
- Manga24h
- Vnsharing
- Blogtruyen
# German
- MangaTube
# Spanish
- SubManga
- MangaHere (ES)
- Batoto (ES)
# Chinese
- 漫画178
# French
- Anime Story
- Batoto (FR)
# Russian
- Readmanga
- MangaRussia
- Manga24 
# Portuguese
- BPT
# Arabic
- MangaAr

**Comment by smad2005** [comment]
Project is `0xDEADBEEF`

**Comment by i2um1** [comment]
The project is alive, I have no time to upload it because of my game mania / hobbies. And I have an extended list of manga/image sites.
Thanks for understanding.

**Comment by smad2005** [comment]
![](https://2ch.hk/dev/arch/wakaba/src/1358020346377.jpg)
